### ISSUE TITLE
Update SILENCE docs

### ISSUE THREAD

**Issue by iwalkalone69** [inspircd/inspircd-docs#16]
There are some flags missing.

Also, it would be great to add an example of how to add/remove a SILENCE but not all flags or how to add an exception.

**Comment by SaberUK** [comment]
Which flags are missing? [This](https://docs.inspircd.org/3/modules/silence/) looks pretty complete.

Fair point about the exceptions though, i'll add that.

**Comment by iwalkalone69** [comment]
When I add a SILENCE with all the flags I get:

SILENCE -patata!*@* :CciNnPpTt

Documented I can see a c i n p t x.

**Comment by SaberUK** [comment]
Seems okay to me? Is your browser overriding the fonts we use?

![](https://user-images.githubusercontent.com/1565825/64249644-10cdf100-cf0c-11e9-930b-78d341640e51.png)

**Comment by SaberUK** [comment]
Are you looking at the v2 page instead of the v3 page?

**Comment by iwalkalone69** [comment]
Nevermind. I was accessing to version 2 and I didn't realize.

But an example with customized flags and exception would be great.
