### ISSUE TITLE
Either <connect:allow> or <connect:deny> is required or connect class is not suitable

### ISSUE THREAD

**Issue by Whissi** [inspircd/inspircd-docs#178]
If you create a config like shown in the following example, https://github.com/inspircd/inspircd-docs/blob/a4368837b09728991287172201d4e45b04e318dd/docs/3/configuration/_connect.yml#L159-L183 you will see the following message in debug mode when a client connects on port `6697`:

```
Tue May 23 2023 03:20:42 CONNECTCLASS: The Secure connect class is not suitable as neither <connect:allow> nor <connect:deny> are set
Tue May 23 2023 03:20:42 CONNECTCLASS: Checking the Main connect class ...
Tue May 23 2023 03:20:42 CONNECTCLASS: The Main connect class is suitable for 007AAAAAF (tester!tester@8-7-6-5-4.example.net)
````

In other words: The example doesn't work. Looks like either `<connect:allow>` or `<connect:deny>` is always required.

Tested with version `3.16.0 [Vendor]`.

**Comment by genius3000** [comment]
Good catch! You are correct that one of `allow` or `deny` are required in a connect class for typical user connection matching. In the referenced example, an `allow="*"` should be added.  
I'll dive a little deeper, for fun, should look at adding this to the docs tbh. Actual requirement is one of `name`, `allow`, or `deny`. These define the **type** for the connect class. An _allow_ or _deny_ type can have a defined name or be nameless and the server will assign it a name. A _named_ type does not contain an `allow` or `deny` value and will not match during the core user connect cycle. These can be used to define a _parent_ (or base) class for various purposes and modules can force a user into a _named_ class.
