### ISSUE TITLE
While on mobile, some links on the main page are behind a hidden element making them unclickable

### ISSUE THREAD

**Issue by Robby-** [inspircd/inspircd-docs#18]
While on mobile, some links on the main page are behind a hidden element making them unclickable.

This is also reproducible on the PC by simply resizing the window to mimic a mobile device/small screen.

Browser: Firefox 69.0.3

Links that become unclickable in mobile view:
`General: Security Advisories`
`General: Versioning Policy`
`InspIRCd 2: Modules`
`InspIRCd 2: SNOMasks`

**Comment by SaberUK** [comment]
This is a theme issue, maybe report it at https://github.com/chrissimpkins/cinder ?

**Comment by SadieCat** [comment]
We're using a more recent theme version now, is this still an issue?

**Comment by Robby-** [comment]
Yes, it still is, Firefox 73.0.1 now. Still easy to reproduce on the computer too, by resizing the window.

**Comment by SadieCat** [comment]
Fixed in commit f8bfafa/
