### ISSUE TITLE
Virtual Host Servers... is it possible to have multiple servers with 1 ip, 1 instance running

### ISSUE THREAD

**Issue by prepstarr** [inspircd/inspircd-docs#64]
I was wondering if it was possible for me to set up different servers with the 1 ip and 1 server, like Virtual Hosts.

**Comment by SadieCat** [comment]
This is not possible. IRC clients do not send the equivalent of a "Host" header (what is used to implement virtual hosts in websites). If you want to run multiple IRC servers on one physical server your best bet is to use separate ports for IPv4 or separate IP addresses for IPv6 (most hosts give a /64 which is plenty).
