### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by rabbit59** [inspircd/inspircd-docs#7]
It seems that the  migration away from wiki has lost a lot of information, an example is the +/-P channel mode. It's not documented under channel modes. Another example is the configuration for the filter module is missing the include directive.

**Comment by SaberUK** [comment]
>an example is the +/-P channel mode. It's not documented under channel mode

As it explicitly says the modes page only documents core modes.  The `P` mode is documented on [the page for the module that provides it](https://docs.inspircd.org/2/modules/permchannels/#channel-modes).

>Another example is the configuration for the filter module is missing the include directive.

The include tag is not specific to the filter module. [The filter module is fully documented](https://docs.inspircd.org/2/modules/filter/).

**Comment by SaberUK** [comment]
As there's been no comments in two weeks i'm going to close this.
